# Generated by Django 5.1.4 on 2025-05-13 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_product_discount_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
