# Generated by Django 5.1.4 on 2025-05-15 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
